### ISSUE TITLE
Click area on links under resources

### ISSUE THREAD

**Issue by lindsaybangs** [CarletonComputerScienceSociety/website-2014#11]
The clickable area around a link is very large and might lead to users clicking a link without intending to.  Eg, myself when I tried to deselect something, clicked a blank area and ended up opening a new tab. 

Minor issue for desktop, but might be an issue for mobile?

Side note: followed links remain highlighted upon returning to the main page tab, until you click something else.

**Comment by Sqash** [comment]
Big click area was intentional but could be easily changed. @connorhillen thoughts?
remaining highlighted was something that was not intentional ~~but I'm not entirely sure why it's the case. Will fix when I have time to read into why it happens.~~

Update: Pretty sure that it's because I've added the color styling to :focus pseudo class of anchors in addition to them being on the :active pseudo class. Focus remains after you click when it opens another tab.

Adding the styles to :focus was for visual rendering uniformity when people navigate by keyboard. I'll test to make sure this is the case, but do we want to remove that visual recognition from keyboard navigation? (it does still get the floaty blue outline technically)

**Comment by lindsaybangs** [comment]
The link area is still too large.

**Comment by Sqash** [comment]
It was reduced by >50%

Only non-jank solution to reduce it further except maybe flexing everything inside:

![image](https://cloud.githubusercontent.com/assets/2488495/8611069/5fbc5af2-2689-11e5-8974-99d9d7f0ab4d.png)

I think it looks gross like that. Will look into flexing everything

**Comment by Sqash** [comment]
flex doesn't help. Still renders h2 100% wide. Explicitly setting the widths of them is a bad idea and will also make the small titles still have extra clickability. ~~Going to try a span solution or something.~~ It's just display:block behaviour to do that apparently.

**Comment by Sqash** [comment]
Alternate solution: Put <br> elements between the <i> and <h2> and set display for <h2> to inline-block.
It actually does everything I think Lindsay wants, but using HTML for changing layout is not a good practice.

**Comment by Sqash** [comment]
Made it all look good inline.
